feat: implement polish function
casbin/casdoc pull request #1
Opened 2023-08-13 13:38 UTC by Selflocking

2023-08-14 04:47 UTC, hsluoyz requested changes

2023-08-14 04:47 UTC, hsluoyz commented on go.mod
> +module casdoc
https://github.com/casbin/casdoc

2023-08-14 04:47 UTC, hsluoyz commented on main.go
> +func PolishDocs() {
main

2023-08-14 04:47 UTC, hsluoyz commented on casdoc_test.go
> +package main
Apache headers for all files

2023-08-14 04:47 UTC, hsluoyz commented on config/config.go
> +	"github.com/spf13/viper"
sort

2023-08-14 15:23 UTC, hsluoyz approved these changes

2023-08-14 15:24 UTC, merged

2023-08-28 17:07 UTC, dirname commented on casdoc_test.go
> +		for {
Consider using more concise code.

```
for counter := 1; !Q.Empty(); counter++ {
	p := Q.Pop()
	Logger = Logger.WithField("rate", fmt.Sprintf("%d/%d", counter, totalItems))
	Logger.Info("Now translate: ", strings.TrimPrefix(p, config.RepoPath))
	if err := utils.Translate(p, lang); err != nil {
		Q.AddToFailedList(p)
		Logger.Errorf("error: %v\n", err)
	}
}
```

2023-08-28 17:08 UTC, dirname commented on main.go
> +	for {
Refer to https://github.com/casbin/casdoc/pull/1/files#r1307692052